//! Serializing an item stream: RSS 2.0, Atom, JSON, CSV.
//!
//! One entry point ([`emit`]) shared by the headless runner and the TUI's
//! RAW preview, so what you see in the editor is byte-for-byte what
//! `ripe-run` writes. Items use the conventional keys (`title`, `link`,
//! `description`, `guid`, `author`, `pubDate`); anything a format cannot
//! express is dropped, never an error — feeds are lossy by nature, and the
//! lossless formats (JSON, CSV) carry every field.

use std::str::FromStr;

use crate::expr::{parse_date, value_text};
use crate::item::Item;

/// An output serialization format (the Output module's `format` param).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Format {
    Rss,
    Atom,
    Json,
    Csv,
}

/// Error for a format name that isn't one of the four.
#[derive(Debug, thiserror::Error, PartialEq, Eq)]
#[error("unknown format `{0}` (expected rss, atom, json, or csv)")]
pub struct ParseFormatError(String);

impl FromStr for Format {
    type Err = ParseFormatError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "rss" => Ok(Format::Rss),
            "atom" => Ok(Format::Atom),
            "json" => Ok(Format::Json),
            "csv" => Ok(Format::Csv),
            other => Err(ParseFormatError(other.to_string())),
        }
    }
}

/// Serialize `items` as `format`, with `feed_title` as the channel/feed
/// title where the format has one. Empty input produces a valid empty
/// document, not an error.
pub fn emit(format: Format, feed_title: &str, items: &[Item]) -> anyhow::Result<String> {
    match format {
        Format::Rss => emit_rss(feed_title, items),
        Format::Atom => emit_atom(feed_title, items),
        Format::Json => emit_json(items),
        Format::Csv => emit_csv(items),
    }
}

/// RSS 2.0 requires a channel link and description; a pipe has neither, so
/// they are filled with an empty string and a fixed byline.
fn emit_rss(feed_title: &str, items: &[Item]) -> anyhow::Result<String> {
    let rss_items: Vec<rss::Item> = items
        .iter()
        .map(|item| {
            let mut out = rss::Item::default();
            out.set_title(item.get_str("title"));
            out.set_link(item.get_str("link"));
            out.set_description(item.get_str("description"));
            out.set_author(item.get_str("author"));
            if let Some(guid) = item.get_str("guid") {
                // Our guids are opaque ids, not guaranteed URLs, so never
                // claim isPermaLink (the RSS default is true).
                out.set_guid(rss::Guid {
                    value: guid,
                    permalink: false,
                });
            }
            // pubDate is stored as RFC 3339; RSS wants RFC 2822. A date we
            // cannot parse is omitted rather than emitted malformed.
            out.set_pub_date(
                item.get_str("pubDate")
                    .and_then(|d| parse_date(&d))
                    .map(|d| d.to_rfc2822()),
            );
            out
        })
        .collect();

    let channel = rss::ChannelBuilder::default()
        .title(feed_title)
        .link("")
        .description("Generated by ripe")
        .items(rss_items)
        .build();
    let bytes = channel.pretty_write_to(Vec::new(), b' ', 2)?;
    let mut text = String::from_utf8(bytes)?;
    text.push('\n');
    Ok(text)
}

fn emit_atom(feed_title: &str, items: &[Item]) -> anyhow::Result<String> {
    let entries: Vec<atom_syndication::Entry> = items
        .iter()
        .map(|item| {
            let mut entry = atom_syndication::Entry::default();
            if let Some(title) = item.get_str("title") {
                entry.set_title(title);
            }
            // Atom requires an id per entry; the link is the conventional
            // fallback when a feed item carried no guid.
            if let Some(id) = item.get_str("guid").or_else(|| item.get_str("link")) {
                entry.set_id(id);
            }
            if let Some(link) = item.get_str("link") {
                let mut l = atom_syndication::Link::default();
                l.set_href(link);
                entry.set_links(vec![l]);
            }
            if let Some(summary) = item.get_str("description") {
                entry.set_summary(Some(atom_syndication::Text::plain(summary)));
            }
            if let Some(author) = item.get_str("author") {
                let mut person = atom_syndication::Person::default();
                person.set_name(author);
                entry.set_authors(vec![person]);
            }
            // RFC 3339 pubDate maps straight onto Atom's updated; entries
            // without one keep the default (epoch).
            if let Some(date) = item.get_str("pubDate").and_then(|d| parse_date(&d)) {
                entry.set_updated(date.fixed_offset());
            }
            entry
        })
        .collect();

    let mut feed = atom_syndication::Feed::default();
    feed.set_title(feed_title.to_string());
    // Atom requires a feed id (an IRI); a pipe has no canonical URI, so the
    // title stands in.
    feed.set_id(feed_title.to_string());
    feed.set_updated(
        entries
            .iter()
            .map(|e| *e.updated())
            .max()
            .unwrap_or_default(),
    );
    feed.set_entries(entries);

    let bytes = feed.write_with_config(
        Vec::new(),
        atom_syndication::WriteConfig {
            write_document_declaration: true,
            indent_size: Some(2),
        },
    )?;
    let mut text = String::from_utf8(bytes)?;
    text.push('\n');
    Ok(text)
}

/// The raw items, pretty-printed. Keys serialize sorted (the underlying map
/// is BTreeMap-backed), so output is deterministic.
fn emit_json(items: &[Item]) -> anyhow::Result<String> {
    let mut text = serde_json::to_string_pretty(items)?;
    text.push('\n');
    Ok(text)
}

/// Headers are the key union across all items (sorted); an item missing a
/// field gets an empty cell. Nested values render as JSON text.
fn emit_csv(items: &[Item]) -> anyhow::Result<String> {
    let headers = Item::key_union(items);
    if headers.is_empty() {
        // No items (or none with fields) means no columns; the csv crate
        // rejects zero-field records, and an empty document is the honest
        // rendering anyway.
        return Ok(String::new());
    }
    let mut writer = csv::Writer::from_writer(Vec::new());
    writer.write_record(&headers)?;
    for item in items {
        let row: Vec<String> = headers
            .iter()
            .map(|key| item.get(key).map(value_text).unwrap_or_default())
            .collect();
        writer.write_record(&row)?;
    }
    Ok(String::from_utf8(writer.into_inner()?)?)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    /// Three items: one with every conventional key plus an extra field,
    /// one with an unparseable date, one nearly empty. Dates are RFC 3339,
    /// as sources store them.
    fn sample_items() -> Vec<Item> {
        [
            json!({
                "title": "First post",
                "link": "https://example.dev/1",
                "description": "Hello, world",
                "guid": "post-1",
                "author": "Ada",
                "pubDate": "2026-06-01T10:00:00+00:00",
                "score": 42,
            }),
            json!({
                "title": "Second post",
                "link": "https://example.dev/2",
                "pubDate": "not a date",
            }),
            json!({
                "title": "Third post",
            }),
        ]
        .into_iter()
        .map(|v| Item(v.as_object().unwrap().clone()))
        .collect()
    }

    #[test]
    fn from_str_accepts_the_four_names_and_nothing_else() {
        assert_eq!("rss".parse(), Ok(Format::Rss));
        assert_eq!("atom".parse(), Ok(Format::Atom));
        assert_eq!("json".parse(), Ok(Format::Json));
        assert_eq!("csv".parse(), Ok(Format::Csv));
        let err = "xml".parse::<Format>().unwrap_err();
        assert_eq!(
            err.to_string(),
            "unknown format `xml` (expected rss, atom, json, or csv)"
        );
    }

    #[test]
    fn rss_snapshot() {
        insta::assert_snapshot!(emit(Format::Rss, "Snapshot Feed", &sample_items()).unwrap());
    }

    #[test]
    fn atom_snapshot() {
        insta::assert_snapshot!(emit(Format::Atom, "Snapshot Feed", &sample_items()).unwrap());
    }

    #[test]
    fn json_snapshot() {
        insta::assert_snapshot!(emit(Format::Json, "Snapshot Feed", &sample_items()).unwrap());
    }

    #[test]
    fn csv_snapshot() {
        insta::assert_snapshot!(emit(Format::Csv, "Snapshot Feed", &sample_items()).unwrap());
    }

    #[test]
    fn empty_items_produce_valid_empty_documents() {
        let rss = emit(Format::Rss, "Empty", &[]).unwrap();
        assert!(rss.contains("<channel>"), "{rss}");
        assert!(!rss.contains("<item>"), "{rss}");

        let atom = emit(Format::Atom, "Empty", &[]).unwrap();
        assert!(atom.contains("<feed"), "{atom}");
        assert!(!atom.contains("<entry>"), "{atom}");

        assert_eq!(emit(Format::Json, "Empty", &[]).unwrap(), "[]\n");
        assert_eq!(emit(Format::Csv, "Empty", &[]).unwrap(), "");
    }
}
