//! Preview snapshot: a precomputed, UI-free view of the pipe's output stream.
//!
//! The TUI's FEED / ITEMS / RAW tabs render from one of these. It is built
//! once per eval, off the render thread, from the Output node's item stream —
//! so the editor view stays a pure function of its model and never
//! re-serializes a feed or reads a clock while drawing.
//!
//! RAW reuses [`crate::format::emit`], so what the editor previews is
//! byte-for-byte what `ripe-run` would write for the same format.

use chrono::{DateTime, Utc};

use crate::expr::parse_date;
use crate::format::{self, Format};
use crate::item::Item;

/// The channel description [`crate::format::emit`] stamps on generated feeds,
/// mirrored here so the FEED tab agrees with the RAW output.
pub const CHANNEL_DESCRIPTION: &str = "Generated by ripe";

/// Channel-level metadata shown on the FEED tab.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FeedMeta {
    pub title: String,
    /// A pipe has no canonical link; `None` renders as a placeholder.
    pub link: Option<String>,
    pub description: String,
    pub format: Format,
}

/// One item rendered as a card (title / domain / age / snippet). Every field
/// is pre-formatted text; empty strings mark absent fields so the view can
/// skip a line without any logic of its own.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ItemCard {
    pub title: String,
    /// Host of the item's `link`, empty when there is none.
    pub domain: String,
    /// Humanized age from `pubDate` (e.g. `2h ago`), empty when unparseable.
    pub age: String,
    /// Whitespace-collapsed `description`, empty when absent.
    pub snippet: String,
}

/// The full precomputed preview of an output stream.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Preview {
    pub feed: FeedMeta,
    pub cards: Vec<ItemCard>,
    /// The serialized feed, produced by [`crate::format::emit`].
    pub raw: String,
    pub count: usize,
    /// When this snapshot was built (the engine's `ctx.now`); drives the
    /// footer's "last eval" clock and keeps age formatting deterministic.
    pub generated_at: DateTime<Utc>,
}

impl Preview {
    /// Build a preview from an output stream. `now` is injected so age
    /// formatting is deterministic (the engine passes its `ctx.now`).
    pub fn build(items: &[Item], format: Format, feed_title: &str, now: DateTime<Utc>) -> Self {
        let cards = items
            .iter()
            .map(|item| ItemCard::from_item(item, now))
            .collect();
        // emit only fails on genuinely un-serializable input (e.g. a CSV with
        // no columns is fine — it returns empty). Surface any error inline
        // rather than dropping the whole preview.
        let raw = format::emit(format, feed_title, items)
            .unwrap_or_else(|e| format!("<could not serialize feed: {e}>\n"));
        Preview {
            feed: FeedMeta {
                title: feed_title.to_string(),
                link: None,
                description: CHANNEL_DESCRIPTION.to_string(),
                format,
            },
            cards,
            raw,
            count: items.len(),
            generated_at: now,
        }
    }

    /// Clock label (HH:MM) for the footer's "last eval time"; kept short so it
    /// fits the preview pane's narrow footer alongside "Rendered N items".
    pub fn updated_label(&self) -> String {
        self.generated_at.format("%H:%M").to_string()
    }
}

impl ItemCard {
    fn from_item(item: &Item, now: DateTime<Utc>) -> Self {
        let title = item
            .get_str("title")
            .filter(|s| !s.is_empty())
            .unwrap_or_else(|| "(untitled)".to_string());
        let domain = item
            .get_str("link")
            .as_deref()
            .and_then(domain_of)
            .unwrap_or_default();
        let age = item
            .get_str("pubDate")
            .as_deref()
            .and_then(parse_date)
            .map(|when| humanize_age(when, now))
            .unwrap_or_default();
        let snippet = item
            .get_str("description")
            .map(|d| collapse_ws(&d))
            .unwrap_or_default();
        ItemCard {
            title,
            domain,
            age,
            snippet,
        }
    }
}

/// The host portion of a URL: scheme, userinfo, port, and path stripped. The
/// leading `www.` is deliberately kept (the mockup shows `www.nushell.sh`).
fn domain_of(link: &str) -> Option<String> {
    let link = link.trim();
    if link.is_empty() {
        return None;
    }
    let after = link.split_once("://").map_or(link, |(_, rest)| rest);
    let host = after.split(['/', '?', '#']).next().unwrap_or("");
    // Strip userinfo (`user@host`) then a `:port` suffix.
    let host = host.rsplit('@').next().unwrap_or(host);
    let host = host.split(':').next().unwrap_or(host).trim();
    (!host.is_empty()).then(|| host.to_string())
}

/// Collapse runs of whitespace to single spaces and trim — feeds routinely
/// carry newlines and indentation inside `description`.
fn collapse_ws(s: &str) -> String {
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// A coarse "N unit ago" for a past instant. Future instants and anything
/// under a minute read as "just now".
fn humanize_age(when: DateTime<Utc>, now: DateTime<Utc>) -> String {
    let secs = (now - when).num_seconds();
    if secs < 60 {
        return "just now".to_string();
    }
    let mins = secs / 60;
    if mins < 60 {
        return format!("{mins}m ago");
    }
    let hours = mins / 60;
    if hours < 24 {
        return format!("{hours}h ago");
    }
    let days = hours / 24;
    if days < 7 {
        return format!("{days}d ago");
    }
    format!("{}w ago", days / 7)
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn item(v: serde_json::Value) -> Item {
        Item(v.as_object().unwrap().clone())
    }

    fn at(s: &str) -> DateTime<Utc> {
        parse_date(s).expect("test date must parse")
    }

    #[test]
    fn domain_strips_scheme_path_and_port_but_keeps_www() {
        assert_eq!(
            domain_of("https://blog.rust-lang.org/2024/index.html").as_deref(),
            Some("blog.rust-lang.org")
        );
        assert_eq!(
            domain_of("http://www.nushell.sh").as_deref(),
            Some("www.nushell.sh")
        );
        assert_eq!(
            domain_of("https://user@news.ycombinator.com:8443/item?id=1").as_deref(),
            Some("news.ycombinator.com")
        );
        // No scheme: treat the whole thing as host-ish.
        assert_eq!(domain_of("example.com/x").as_deref(), Some("example.com"));
        assert_eq!(domain_of("   ").as_deref(), None);
    }

    #[test]
    fn humanize_age_covers_each_unit() {
        let now = at("2026-07-05T12:00:00+00:00");
        assert_eq!(
            humanize_age(at("2026-07-05T11:59:30+00:00"), now),
            "just now"
        );
        assert_eq!(
            humanize_age(at("2026-07-05T11:30:00+00:00"), now),
            "30m ago"
        );
        assert_eq!(humanize_age(at("2026-07-05T09:00:00+00:00"), now), "3h ago");
        assert_eq!(humanize_age(at("2026-07-03T12:00:00+00:00"), now), "2d ago");
        assert_eq!(humanize_age(at("2026-06-20T12:00:00+00:00"), now), "2w ago");
        // A future timestamp does not underflow.
        assert_eq!(
            humanize_age(at("2026-07-05T13:00:00+00:00"), now),
            "just now"
        );
    }

    #[test]
    fn collapse_ws_flattens_internal_whitespace() {
        assert_eq!(collapse_ws("  a\n\t b   c "), "a b c");
    }

    #[test]
    fn build_produces_cards_raw_and_meta() {
        let now = at("2026-07-05T12:00:00+00:00");
        let items = vec![
            item(json!({
                "title": "Introducing Rust 1.78",
                "link": "https://blog.rust-lang.org/2024/rust-1-78.html",
                "description": "Rust 1.78.0 is now  available!\nThis release includes performance...",
                "pubDate": "2026-07-05T10:00:00+00:00",
            })),
            item(json!({ "title": "No link, no date" })),
        ];
        let pv = Preview::build(&items, Format::Rss, "Temp RSS", now);

        assert_eq!(pv.count, 2);
        assert_eq!(pv.feed.title, "Temp RSS");
        assert_eq!(pv.feed.format, Format::Rss);
        assert_eq!(pv.feed.description, CHANNEL_DESCRIPTION);

        assert_eq!(pv.cards[0].title, "Introducing Rust 1.78");
        assert_eq!(pv.cards[0].domain, "blog.rust-lang.org");
        assert_eq!(pv.cards[0].age, "2h ago");
        assert_eq!(
            pv.cards[0].snippet,
            "Rust 1.78.0 is now available! This release includes performance..."
        );

        // Missing fields collapse to empty strings, not errors.
        assert_eq!(pv.cards[1].title, "No link, no date");
        assert!(pv.cards[1].domain.is_empty());
        assert!(pv.cards[1].age.is_empty());
        assert!(pv.cards[1].snippet.is_empty());

        // RAW is exactly what the RSS emitter produces.
        assert_eq!(
            pv.raw,
            format::emit(Format::Rss, "Temp RSS", &items).unwrap()
        );
        assert!(pv.raw.contains("<title>Introducing Rust 1.78</title>"));
    }

    #[test]
    fn build_respects_the_chosen_format() {
        let now = at("2026-07-05T12:00:00+00:00");
        let items = vec![item(json!({"title": "a"}))];
        let pv = Preview::build(&items, Format::Json, "T", now);
        assert_eq!(pv.feed.format, Format::Json);
        assert!(pv.raw.trim_start().starts_with('['), "json raw: {}", pv.raw);
    }

    #[test]
    fn updated_label_is_clock_time() {
        let now = at("2026-07-05T12:41:08+00:00");
        let pv = Preview::build(&[], Format::Rss, "T", now);
        assert_eq!(pv.updated_label(), "12:41");
        assert_eq!(pv.count, 0);
    }
}
